"""add more columns and game table

Revision ID: 9cb6a522d5dd
Revises: 54434a2bcf07
Create Date: 2025-08-30 16:36:53.418656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cb6a522d5dd'
down_revision: Union[str, Sequence[str], None] = '54434a2bcf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('final_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_draw', sa.Boolean(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('player1_move_count', sa.Integer(), nullable=False),
    sa.Column('player2_move_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loser_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('losses', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('draws', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'draws')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'wins')
    op.drop_table('game')
    # ### end Alembic commands ###
